### ISSUE TITLE
Guru Meditation Error when using Waveshare TFT library files with newer esp32 firmware (Solved)

### ISSUE THREAD

**Issue by dustinbolton** [jonpul/ESP32-Glance-Display#2]
The Waveshare library config files need updating to work with newer ESP32 firmware versions. Using your included files probably would have saved me from this problem but I didn't read directions well. However, I found other people having this issue with other projects so I figure it would be good to document this somewhere in case others have this issue with this same hardware. Or if someone else fails to follow directions and uses the Waveshare library they can find what they messed up.

Please feel free to mark this as closed so it can just be here for reference/search. Thank you for sharing this great project btw!

Upon uploading the code I got a continuous reboot issue with the following logged to serial:
```
22:24:29.268 -> load:0x3fce3808,len:0x4bc
22:24:29.268 -> load:0x403c9700,len:0xbd8
22:24:29.268 -> load:0x403cc700,len:0x2a0c
22:24:29.268 -> entry 0x403c98d0
22:24:29.808 -> Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.
22:24:29.840 -> 
22:24:29.841 -> Core  1 register dump:
22:24:29.841 -> PC      : 0x42006cef  PS      : 0x00060830  A0      : 0x82006dc4  A1      : 0x3fcebcc0  
22:24:29.874 -> A2      : 0x00000010  A3      : 0x00000000  A4      : 0x60004000  A5      : 0x0000000b  
22:24:29.874 -> A6      : 0x000000ff  A7      : 0x3fc9a940  A8      : 0x08000000  A9      : 0x3fcebc90  
22:24:29.874 -> A10     : 0x3fc9a6c0  A11     : 0x00000001  A12     : 0xffffffff  A13     : 0x00004000  
22:24:29.874 -> A14     : 0x00000000  A15     : 0x3fc94cb0  SAR     : 0x00000010  EXCCAUSE: 0x0000001d  
22:24:29.874 -> EXCVADDR: 0x00000010  LBEG    : 0x42012a88  LEND    : 0x42012a97  LCOUNT  : 0x00000000  
22:24:29.907 -> 
22:24:29.907 -> 
22:24:29.907 -> Backtrace: 0x42006cec:0x3fcebcc0 0x42006dc1:0x3fcebcf0 0x4200537a:0x3fcebd10 0x42013aee:0x3fcebd40
22:24:29.907 -> 
22:24:29.907 -> 
22:24:29.907 -> 
22:24:29.907 -> 
22:24:29.907 -> ELF file SHA256: a1233f12ab2127f0
22:24:29.907 -> 
22:24:30.103 -> Rebooting...
```

I could get it working if I used the esp32 firmware 2.0.12 (Waveshare wiki recommends this version to avoid problems) but not newer (e.g. 2.0.16, 3.x, etc). To get it to work with the latest (3.0.4 currently) I did the following as per a reddit post:

in `Documents/Arduino/libraries/TFT_eSPI/User_Setup_Select.h` file comment out the line (27):
```
#include <User_Setup.h> // Default setup is root library folder
```
as there is already a line (158) at the bottom of the block that says:
```
#include <../TFT_eSPI_Setups/Setup207_GC9A01.h>
```

Now in the `TFT_eSPI_Setups/Setup207_GC9A01.h` file add the following to the bottom of the file:
```
#define USE_HSPI_PORT
```

Notes:
Reddit source: https://www.reddit.com/r/arduino/comments/1bsl0l5/waveshare_esp32s3_128in_lcd_display_with_wifi/
Post that led me to the fix on Reddit: https://github.com/Bodmer/TFT_eSPI/discussions/3283

**Comment by jonpul** [comment]
Great comments! Thanks for sharing this.
